### PR TITLE
Add more clock choices

### PR DESCRIPTION
**Pull request by phi-gamma**
Add support for

       CLOCK_BOOTTIME
       CLOCK_REALTIME_ALARM
       CLOCK_BOOTTIME_ALARM

by introducing an enum for specifying the clock. Includes convenience
printers.

### CODE REVIEW

**Comment by phi-gamma** [comment]
I had to adapt the ``struct timespec`` to work on x86.

**Review by main-- — CHANGES_REQUESTED** [review]
It's a breaking change but a minor one so it's fine (I want to release 1.0.0 anyways).

The `Clockid` enum needs doc comments, just copy them from the manpage (also perhaps `ClockId` might be a better name?).

I'm not sure why your `Display` implementation prints the numeric value. When would one even need that? And even then I feel like it would be more appropriate for `Debug`. I don't really care about this though.

>I had to adapt the `struct timespec` to work on x86.

Can you elaborate? What was broken? What exactly did you have to change?

**Comment by phi-gamma** [comment]
> I'm not sure why your Display implementation prints the numeric value. When would one even need that? And even then I feel like it would be more appropriate for Debug.

I needed the values for comparing with the API headers but you’re right, this should go into Debug.

> I had to adapt the struct timespec to work on x86.

I was referring to this change: https://github.com/main--/rust-timerfd/pull/1/files#diff-092c856d3d35b992e4237543e80e9ad3L33 which was necessary to build it on 32 bits. Without it, rustc gives

    Compiling timerfd v0.2.0
    error[E0308]: mismatched types
      --> /home/phg/.cargo/registry/src/github.com-1ecc6299db9ec823/timerfd-0.2.0/src/structs.rs:33:21
       |
    33 |             tv_sec: d.as_secs() as i64,
       |                     ^^^^^^^^^^^^^^^^^^ expected i32, found i64
    
    error[E0308]: mismatched types
      --> /home/phg/.cargo/registry/src/github.com-1ecc6299db9ec823/timerfd-0.2.0/src/structs.rs:34:22
       |
    34 |             tv_nsec: d.subsec_nanos() as i64, // XXX BUG
       |                      ^^^^^^^^^^^^^^^^^^^^^^^ expected i32, found i64
    
    error: aborting due to 2 previous errors
    
    error: Could not compile `timerfd`.

I’ll update the PR.

**Comment by main--** [comment]
I don't remember exactly what I was thinking there but I added the "XXX BUG" comment because I was unsure about overflow checking (and that's probably also why I didn't cast to the libc typedefs right away). AFAICS `std::time::Duration` actually supports a full `u64` for the seconds part (at least that's what the docs specify) which is already one bit more than the `i64` we need here on x64 and obviously significantly more than the `i32` that's (apparently) only supported on x86. Technically, the same goes for the nanos part but at least this should always be less than one billion so a straight cast here is probably fine. Seconds however clearly need an overflow check. If you want to implement it, go ahead. But I'd merge this even if you don't, it's just one more thing blocking a 1.0.0 release.

**Comment by phi-gamma** [comment]
I didn’t touch the ``Duration`` part. Instead I took a shot at the flags
to ``timerfd_settime()`` which should be present. This is another
API change but should be done before 1.x.

**Review by main-- — CHANGES_REQUESTED** [review]
I know this is getting a little nitpicky but why aren't you just documenting the enum variants directly like [this](https://github.com/main--/rust-timerfd/blob/5abc925732f7cb8842a4fa246a6eb56afa589f46/src/lib.rs#L64-L80)?

**Comment by phi-gamma** [comment]
Better?

**Comment by main--** [comment]
Awesome, thanks!

**Pull request merged**
